CREATE TABLE `MEMBER`
(
    `EMAIL`    VARCHAR(30) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL,
    `ADDRESS`  VARCHAR(50) NOT NULL,
    `POST_NUM` INT         NOT NULL,
    `ROLE`     VARCHAR(10) NOT NULL,
    `ENABLED`  BOOLEAN     NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE `ORDERS`
(
    `ORDER_NUM`     INT         NOT NULL AUTO_INCREMENT,
    `EMAIL`         VARCHAR(30) NOT NULL,
    `ADDRESS`       VARCHAR(50) NOT NULL,
    `POST_NUM`      INT         NOT NULL,
    `ORDER_TIME`    DATETIME    NOT NULL,
    PRIMARY KEY (ORDER_NUM)
);

CREATE TABLE `COFFEE`
(
    `COFFEE_ID`     INT NOT NULL AUTO_INCREMENT,
    `COFFEE_NAME`   VARCHAR(30) NOT NULL,
    `PRICE`         INT         NOT NULL,
    `STOCK`         INT         NOT NULL,
    PRIMARY KEY (COFFEE_ID)
);

CREATE TABLE `DETAIL`
(
    `DETAIL_NUM` INT NOT NULL AUTO_INCREMENT,
    `ORDER_NUM`  INT NOT NULL,
    `COFFEE_ID`  INT NOT NULL,
    `QUANTITY`   INT NOT NULL,
    PRIMARY KEY (DETAIL_NUM),
    FOREIGN KEY (ORDER_NUM) REFERENCES `ORDERS` (ORDER_NUM),
    FOREIGN KEY (COFFEE_ID) REFERENCES `COFFEE` (COFFEE_ID)
);